<?php
use yii\helpers\Html;
echo Html::beginTag('ul',['class' => 'list-unstyled']);
	echo Html::beginTag('li',['name' => 'category-slider','slider' => '1', 'status' => 'active']);
		echo Html::beginTag('div',['class' => 'row row-single-category']);
			echo Html::beginTag('div',['class' => 'col-xs-12 col-sm-10 col-single-category']);
				echo Html::beginTag('div',['class' => 'row']);
					echo Html::beginTag('div',['class' => 'col-xs-12']);
						echo Html::beginTag('span',['class' => 'icon']);
							echo Html::tag('i','',['class' => 'fa fa-circle', 'aria-hidden' => 'true']);
						echo Html::endTag('span');
						echo Html::beginTag('span',['class' => 'title']);
							echo 'Вертикальные жалюзи';
						echo Html::endTag('span');
					echo Html::endTag('div');
					echo Html::beginTag('div',['class' => 'col-xs-12 text-right']);
						echo Html::beginTag('span',['class' => 'price']);
							echo 'от'.Html::tag('span','1231',['class' => 'number']).Html::tag('span','руб',['class' => 'rub']);
						echo Html::endTag('span');

					echo Html::endTag('div');
				echo Html::endTag('div');
			echo Html::endTag('div');
			echo Html::beginTag('div',['class' => 'col-sm-2 hidden-xs']);
				echo Html::img('@web/images/slider/vertical-blinds/category/1.jpg',['class' => 'img-category']);
			echo Html::endTag('div');
		echo Html::endTag('div');
	echo Html::endTag('li');
	echo Html::beginTag('li',['name' => 'category-slider','slider' => '2']);
		echo Html::beginTag('div',['class' => 'row row-single-category']);
			echo Html::beginTag('div',['class' => 'col-xs-12 col-sm-10 col-single-category']);
				echo Html::beginTag('div',['class' => 'row']);
					echo Html::beginTag('div',['class' => 'col-xs-12']);
						echo Html::beginTag('span',['class' => 'icon']);
							echo Html::tag('i','',['class' => 'fa fa-circle', 'aria-hidden' => 'true']);
						echo Html::endTag('span');
						echo Html::beginTag('span',['class' => 'title']);
							echo 'Пластиковые вертикальные жалюзи';
						echo Html::endTag('span');
					echo Html::endTag('div');
					echo Html::beginTag('div',['class' => 'col-xs-12 text-right']);
						echo Html::beginTag('span',['class' => 'price']);
							echo 'от'.Html::tag('span','1231',['class' => 'number']).Html::tag('span','руб',['class' => 'rub']);
						echo Html::endTag('span');

					echo Html::endTag('div');
				echo Html::endTag('div');
			echo Html::endTag('div');
			echo Html::beginTag('div',['class' => 'col-sm-2 hidden-xs']);
				echo Html::img('@web/images/slider/vertical-blinds/category/2.jpg',['class' => 'img-category']);
			echo Html::endTag('div');
		echo Html::endTag('div');
	echo Html::endTag('li');
	echo Html::beginTag('li',['name' => 'category-slider','slider' => '3']);
		echo Html::beginTag('div',['class' => 'row row-single-category']);
			echo Html::beginTag('div',['class' => 'col-xs-12 col-sm-10 col-single-category']);
				echo Html::beginTag('div',['class' => 'row']);
					echo Html::beginTag('div',['class' => 'col-xs-12']);
						echo Html::beginTag('span',['class' => 'icon']);
							echo Html::tag('i','',['class' => 'fa fa-circle', 'aria-hidden' => 'true']);
						echo Html::endTag('span');
						echo Html::beginTag('span',['class' => 'title']);
							echo 'Мультифактурные';
						echo Html::endTag('span');
					echo Html::endTag('div');
					echo Html::beginTag('div',['class' => 'col-xs-12 text-right']);
						echo Html::beginTag('span',['class' => 'price']);
							echo 'от'.Html::tag('span','1231',['class' => 'number']).Html::tag('span','руб',['class' => 'rub']);
						echo Html::endTag('span');

					echo Html::endTag('div');
				echo Html::endTag('div');
			echo Html::endTag('div');
			echo Html::beginTag('div',['class' => 'col-sm-2 hidden-xs']);
				echo Html::img('@web/images/slider/vertical-blinds/category/3.jpg',['class' => 'img-category']);
			echo Html::endTag('div');
		echo Html::endTag('div');
	echo Html::endTag('li');
	echo Html::beginTag('li',['name' => 'category-slider','slider' => '4']);
		echo Html::beginTag('div',['class' => 'row row-single-category']);
			echo Html::beginTag('div',['class' => 'col-xs-12 col-sm-10 col-single-category']);
				echo Html::beginTag('div',['class' => 'row']);
					echo Html::beginTag('div',['class' => 'col-xs-12']);
						echo Html::beginTag('span',['class' => 'icon']);
							echo Html::tag('i','',['class' => 'fa fa-circle', 'aria-hidden' => 'true']);
						echo Html::endTag('span');
						echo Html::beginTag('span',['class' => 'title']);
							echo 'Бриз';
						echo Html::endTag('span');
					echo Html::endTag('div');
					echo Html::beginTag('div',['class' => 'col-xs-12 text-right']);
						echo Html::beginTag('span',['class' => 'price']);
							echo 'от'.Html::tag('span','1231',['class' => 'number']).Html::tag('span','руб',['class' => 'rub']);
						echo Html::endTag('span');

					echo Html::endTag('div');
				echo Html::endTag('div');
			echo Html::endTag('div');
			echo Html::beginTag('div',['class' => 'col-sm-2 hidden-xs']);
				echo Html::img('@web/images/slider/vertical-blinds/category/4.jpg',['class' => 'img-category']);
			echo Html::endTag('div');
		echo Html::endTag('div');
	echo Html::endTag('li');
echo Html::endTag('ul');

?>

