<?php
use yii\helpers\Html;
echo Html::beginTag('div',['class' => 'row']);
	echo Html::beginTag('div',['class' => 'col-xs-12 category-title']);
		echo "Акация";
	echo Html::endTag('div');
echo Html::endTag('div');
echo Html::beginTag('div',['class' => 'row top-10']);
	echo Html::beginTag('div',['class' => 'col-xs-4 material', 'price' => '1200']);
		echo Html::beginTag('ul',['class' => 'list-unstyled']);
			echo Html::beginTag('li',['class' => 'title-material']);
				echo Html::beginTag('ul',['class' => 'list-inline']);
					echo Html::beginTag('li',['class' => 'code']);
						echo "012";
					echo Html::endTag('li');
					echo Html::beginTag('li',['class' => 'price']);
						echo Html::tag('span','1200',['class' => 'number']);
						echo Html::tag('span','руб/м2',['class' => 'rub']);
					echo Html::endTag('li');
				echo Html::endTag('ul');
			echo Html::endTag('li');
			echo Html::beginTag('li',['class' => 'image-material']);
				echo Html::img('@web/images/material/акация/300303-2261.jpg',['class' => 'img-responsive']);
			echo Html::endTag('li');
			echo Html::beginTag('li',['class' => 'description-material']);
				echo "Название";
			echo Html::endTag('li');
		echo Html::endTag('ul');
	echo Html::endTag('div');
	echo Html::beginTag('div',['class' => 'col-xs-4 material', 'price' => '1300']);
		echo Html::beginTag('ul',['class' => 'list-unstyled']);
			echo Html::beginTag('li',['class' => 'title-material']);
				echo Html::beginTag('ul',['class' => 'list-inline']);
					echo Html::beginTag('li',['class' => 'code']);
						echo "012";
					echo Html::endTag('li');
					echo Html::beginTag('li',['class' => 'price']);
						echo Html::tag('span','1300',['class' => 'number']);
						echo Html::tag('span','руб/м2',['class' => 'rub']);
					echo Html::endTag('li');
				echo Html::endTag('ul');
			echo Html::endTag('li');
			echo Html::beginTag('li',['class' => 'image-material']);
				echo Html::img('@web/images/material/акация/300303-1606.jpg',['class' => 'img-responsive']);
			echo Html::endTag('li');
			echo Html::beginTag('li',['class' => 'description-material']);
				echo "Название";
			echo Html::endTag('li');
		echo Html::endTag('ul');
	echo Html::endTag('div');
echo Html::endTag('div');
?>
